- fbchat/client.py
added param to allow for the ability to send messages to group chats using thread_id. if param is not used, defaults to sending to user_id
> added param for group messages

- fbchat/client.py
Solution for #51 where `content` received in `parseMessage` is always {u'reason': 110, u't': u'refresh', u'seq': 0} which makes `on_message` never fire.
Also added some docstrings that instruct users to subclass Client and override the event handlers to have custom behaviour.
> added clientid to data to fix listening issue

- fbchat/client.py
Due to issue #92 , this one should do.
You can logout() then login() without having to create new Client. Create new Client is ok too.
Example:
```
client = fbchat.Client("Yourname", "Yourpwd")
client.logout()
client.login()
```
By the way, you will have to pull #77 first to make fbchat works properly.
Keep in mind that, in multi-thread program, you will have to manage thread and lock yourself to make sure that you don't send message while logout.
> Add logout feature

- fbchat/client.py
In python3 requests.session().[get|post]()._content gives a bytes object. We have to decode it into a string in order to use it in the code. Otherwise calling `fbchat.Client.uploadImage` results in an error:
```
Traceback (most recent call last):
File "main.py", line 49, in send_all
send_result(client, user, message)
File "main.py", line 18, in send_result
client.sendRemoteImage(user, message=data["pre"], image=data["img"])
File "/home/maks/Documents/ComicMessenger/venv/lib/python3.5/site-packages/fbchat/client.py", line 305, in sendRemoteImage
image_id = self.uploadImage({'file': (image, remote_image, mimetype)})
File "/home/maks/Documents/ComicMessenger/venv/lib/python3.5/site-packages/fbchat/client.py", line 329, in uploadImage
return …
```
> Fixes the issue #60 for Python3

- fbchat/client.py
Facebook now requires channel and clientid to be passed when requesting a sticky pool.
> Fixed _getSticky

- fbchat/client.py
This can be configured externally, to be decided by the developer.
Remove 'print's and calls to the 'Client._console' method.
The 'Client._console' method still exists, but it creates a DeprecationWarning and log the message at the logging.INFO level.
> Add a logger (from 'logging') to log events.

- fbchat/client.py
https://github.com/carpedm20/fbchat/issues/86
According to this issue, I take a look at the code and notice that listening didn't set encoding to 'UTF-8'. Setting to UTF-8 should fix encoding issue.
Testing the latin alphabet and thai alphabet, both seem to work correctly.
> Fix fb listening encoding

- fbchat/client.py
Sometimes Facebook tries to show the user a "Save Device" dialog.
This may also help fixing #58
> Improved login reliability

- fbchat/client.py
- Refactored `getThreadList` parameter `end` which is ignored by the `_post` method if `end > 20`.
- Refactored `getThreadInfo` parameter `start` which is ignored, messages are always returned from the last message with 0 index.
- Renamed `getThreadInfo` parameter `end` to `length` which better represents the behaviour
- updated `getUserInfo` to accept both:
- string IDs starting with `fbid:`  produced by entries of `messages = client.getThreadInfo(...)`
- string IDs produced by `client.getUsers('<friend name>')[0].uid` 
assertion error is thrown when parameters are used improperly
> Query ignore fix

- fbchat/client.py
I think that this bug occurs because some users have bugged contact lists, so I added this try block to ignore such contacts.
> fixed a bug that prevented fbchat from returning the list of all users

- fbchat/client.py
The participants property on thread object is returning a list of unicodes. If you then pass these unicodes to getUserInfo, they are not being picked up in the if statement on line 905 in the fbidStrip method, so the fbidStrip method was returning a tuple of None objects. The conditional now matches and reformats both str and unicode objects.
> Fix for getUserInfo method throwing an error

- README.rst
- fbchat/client.py
Fixes #126 
Updated readme, and changed `getThreadInfo`, so `last_n` actually specifies the amount of retrieved messages
> Fixes #126

- .gitignore
- fbchat/client.py
- fbchat/event_hook.py
- fbchat/models.py
- fbchat/utils.py
- test_data.json
- tests.py
Size should be EmojiSize so not to cause confusion
IMO we should ditch all deprecation warnings, make it backwards-incompatible and bump to version 1.0 once I add more chat methods. there is no correct way to keep on_* methods with a warning, they would be called everytime and generate the warning everytime for everyone. this is like dragging a dead horse around.
> reintroduce things skipped on conflict

- fbchat/client.py
It sidesteps the log() feature, but at least now you get which file and at what line the error occurred.
Previous error could look something like this: `name 'unicode' is not defined`
Now you'll get: 
File "/usr/lib/python3.6/site-packages/fbchat-0.10.1-py3.6.egg/fbchat/client.py", line 900, in fbidStrip
if type(_fbid) in [str, unicode] and 'fbid:' in _fbid:
NameError: name 'unicode' is not defined
> Swapped out for a better error output.

- fbchat/client.py
- fbchat/graphql.py
- fbchat/models.py
Add a new field for fb share objects (like videos, links, pictures shared from Facebook to a messenger thread). Modeled it off the attachments field, which just takes the dict from the graphql response.
E.g. turns this:
into this:
```
'extensible_attachment':{  
u'story_attachment':{  
u'description':{  
u'text':u'HyperTrack\u2019s Founder & CEO,
Kashyap Deorah,
had me hooked based solely on his previous exploits,
but his fledgling start up,
HyperTrack\u2026'
},
u'url':u'https://l.facebook.com/l.php?u=https%3A%2F%2Fmedium.com%2F%40kevinhartz%2Ffounders-fund-is-excited-to-announce-an-investment-from-our-ff-angel-fund-in-hypertrack-7e309d711c5f&h=ATOp95t7VdT5iME8E1rymEVax-d_Q0Yu7z2OXYs9aZ6gplMGYg7_5BHUswNtTnJK3CPE5zbXA0JyZYmfR8fLlOzHJgOYoL9xGitGD9PtbreZhbfH2OACBM_b9Y8L5Il_3hoBoIrbbds0UL0&s=1 …
```
> Add extensible_attachment field to Message for fb share objects

- fbchat/client.py
Last_seen time stamps were handled in unknown message type, this info is freely available and potentially useful
Allows for some nasty stuff, like tracking your friend's online patterns and deduce their lives
Just popped online and offline again -> probably checked a message on phone
Usually online from 20:00 to 01:00 but not today ->  wasnt home
Usually offline from 01:00 to 10:00 -> sleep time
disclaimer: i was using this by over-riding the class in my code so i know it works, however i edited the code quickly on browser without testing to make this PR
> Add on chat presence event

- setup.py
In setup.py
There is no FileNotFoundError in Python2
However, since we don't do anything with exception anyway, using IOError is clean and work for both py2 and py3.
> No FileNotFoundError in py2

- fbchat/client.py
- fbchat/graphql.py
- fbchat/models.py
- fbchat/utils.py
#175 (502 response):
You would get either a 502 or a 503 response from Facebook's pull-servers once in a while.
Proposed fix is to change the pull-channel, and refresh the `self.sticky`/`self.pool` parameters.
I don't quite remember my tests, but I'm pretty sure that refreshing the sticky/pool parameters were nescessary. I'm not sure I actually double-checked that changing the pull-channel was nescessary, but it's something that I've noticed the Facebook-webclient does.
Other than that:
- The default `doOneListen` loop has been improved.
- Added custom exceptions `FBchatException`, `FBchatFacebookError` and `FBchatUserError`
- Using the custom exceptions, this fixes the "Please try closing and re-opening your browser window" error
- Changed `ReqUrl` to `self.req_url`, so that we can …
> Possibly fixes #175, added custom Exception classes

- fbchat/client.py
- fbchat/models.py
Add "type" parameter to fetchThreadList().
type can be 'inbox', 'pending' or 'archived'
If set to 'pending', it can fetch messages from unknown users.
It is quite useful to build a service accepting requests from anyone.
For example, in doOneListen(), fetch pending messages once for a while
to handle the messages from strangers.
> Enable fetching pending/archived threads

- requirements.txt
- setup.py
As per https://github.com/pypa/pip/issues/4747#issuecomment-333391403
> Updates setup.py for better compatibility with setuptools

- fbchat/client.py
- fbchat/graphql.py
- fbchat/models.py
> Python’s default arguments are evaluated once when the function is defined, not each time the function is called. This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.
http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments
> fixed all mutable default argument gotchas

- fbchat/graphql.py
- fbchat/models.py
Add last_message_timestamp support for one to one and group conversations.
Close #264
> Add last_message_timestamp support

- fbchat/graphql.py
When the returned `short_name` is null, `fbchat` throws an exception:
```python
File "/usr/local/lib/python2.7/site-packages/fbchat/client.py", line 792, in fetchThreadList
return [graphql_to_thread(node) for node in j['viewer']['message_threads']['nodes']]
File "/usr/local/lib/python2.7/site-packages/fbchat/graphql.py", line 193, in graphql_to_thread
last_name=user.get('name').split(user.get('short_name'),1)[1].strip(),
IndexError: list index out of range
```
This commit fixes that scenario by accessing the last item in the list via `.pop()` instead of via `[1]`
> Fix `IndexError: list index out of range` bug

- fbchat/client.py
- fbchat/utils.py
fb_dtsg is sometimes returned inside an HTML comment, and beautifulsoup can't find it - in that case we'll use a regular expression to extract it.
fb_h is sometimes not returned in the HTML of req_url.BASE (in my experience, when resuming a session using session_cookies).
Following the discussion here:
Schmavery/facebook-chat-api#505
I learned it is used for logging out, and can be found in the response of `https://www.facebook.com/bluebar/modern_settings_menu/`.
I included support for fetching it from there.
Because this library is used many more times for logging in, than for logging out, instead of adding an extra HTTP request during login, I decided to perform it during logout, only in case fb_h was not previously found in the HTML of req_url.BASE.
> Make obtaining fb_h and fb_dtsg more versatile

- fbchat/client.py
This change eliminates requesting and downloading the entire FB home page (~160kb) every login.
Another HTTP request can be eliminated when logging in using session cookies by removing ` or not self.isLoggedIn()` from line 74 of client.py, because if the session_cookies are not valid, `setSession()` would surely return False, because of the many exceptions that `_postLogin()` will be throwing.
What do you think?
> Eliminate an unnecessary HTTP request during login

- fbchat/models.py
Resolve the error `fbchat.models.FBchatException: Could not get ThreadColor from color: FF0084FF` when threadcolor is set to default (MESSENGER_BLUE)
> Fix: Resolve FBChatException

- fbchat/client.py
- tests/test_thread_interraction.py
FB changed the format of typing notification messages:
- update "mtype" from "typ" to "ttyp".
- Get thread ID from "to" to "thread_fbid" ("thread" looks the same)
> Fix onTyping detection

- fbchat/client.py
- requirements.txt
- setup.py
After my server has been running for some time, fbchat starts throwing the following exception:
```
Failed loading session
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 366, in setSession
self._postLogin()
File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 212, in _postLogin
soup = bs(r.text, "lxml")
File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 215, in __init__
self._feed()
File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 239, in _feed
self.builder.feed(self.markup)
File "/usr/lib/python2.7/dist-packages/bs4/builder/_lxml.py", line 240, in feed
self.parser.feed(markup)
File "src/lxml/parser.pxi", line 1194, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:119773)
File …
```
> Replace lxml with Python's built in html.parser

- fbchat/graphql.py
There is an edge case for what I believe is deleted accounts where the _name_ attribute is an empty string and the _short_name_ attribute is None, which will result in an IndexError:
```
/anaconda3/lib/python3.6/site-packages/fbchat/graphql.py in graphql_to_thread(thread)
193             name=user.get('name'),
194             first_name=user.get('short_name'),
--> 195             last_name=user.get('name').split(user.get('short_name'),1).pop().strip(),
196             is_friend=user.get('is_viewer_friend'),
197             gender=GENDERS.get(user.get('gender')),
IndexError: pop from empty list
```
> Fix: Name edge case results in IndexError

- fbchat/client.py
This commit fixes the 2FA. Currently we check for the string "enter security code to continue" which is only there for the english page of FB.
> Fix 2FA for non english FB

- fbchat/client.py
When listening, even with `markAlive` parameter set to `True`,
user was active only for a short while.
I fixed this, and now it works fine.
> `markAlive` fix

- fbchat/client.py
- fbchat/models.py
As in #337 I've added new `read_by` attribute to the `Message` model. Actually it only works with `fetchThreadMessages`.
```py
message = client.fetchThreadMessages(thread_id="xxxxxx", thread_type=ThreadType.GROUP)[0]
print(message.read_by)
["xxxxxx", "yyyyyy", "zzzzzz"] # User IDs who read the message
```
> [Feature] New `read_by` attribute of `Message`

- fbchat/client.py
- fbchat/graphql.py
Instead of keeping the results for a search query limited to 1, increased it to 10.
Line changed:
https://github.com/carpedm20/fbchat/blob/89a277c3541e5b5a5a1b4c1dd6aaf9025ce43707/fbchat/client.py#L505
> Fix for issue #365

- .travis.yml
Now we automatically deploy a draft to GitHub Releases on new tags. This is mostly a shortcut for uploading the source and `wheel` distributions
> Automatic GitHub Releases

- fbchat/models.py
Added `formatMentions` method, that makes mentioning a lot easier.
It works exactly like [format](https://pyformat.info/) method but it takes
as parameters tuples with thread id and text. `(thread_id, text)`
```py
Message.formatMentions("Hey {!r}! My name is {}", ("1234", "Peter"), ("4321", "Michael"))
```
`<Message (None): "Hey 'Peter'! My name is Michael", mentions=[<Mention 1234: offset=4 length=7>, <Mention 4321: offset=24 length=7>] emoji_size=None attachments=[]>`
---
```py
Message.formatMentions("Hey {p}! My name is {}", ("1234", "Michael"), p=("4321", "Peter"))
```
`<Message (None): 'Hey Peter! My name is Michael', mentions=[<Mention 4321: offset=4 length=5>, <Mention 1234: offset=22 length=7>] emoji_size=None attachments=[]>`
* Add documentation
* Optimize code if possible
> [Feature] `formatMentions` method

- fbchat/client.py
Currently, fetchUnread() and fetchUnseen() only include 1:1 threads, and not group threads.
Example response from Facebook:
```
{
'__ar':1,
'payload':{
'unread_thread_fbids':[
{
'thread_fbids':[
'[redacted]' // <= Group chats
],
'other_user_fbids':[
'[redacted]' // <= 1:1 chats
],
'thread_ids':[
'[redacted]',
'[redacted]'
],
'folder':'inbox'
}
],
'payload_source':'server_unread_threads'
},
'bootloadable':{},
'ixData':{ },
'bxData':{},
'gkxData':{},
'qexData':{},
'lid':'[redacted]'}
``` 
This pull request changes the behavior of fetchUnseen() and fetchUnread() to include both.
> Correct fetchUnread and fetchUnseen to include 1:1 chats and group chats

- fbchat/_client.py
Builds upon #406
A lot of changes to the variables in `Client`:
Privatized:
- `default_thread_id`
- `default_thread_type`
- `client_id`
- `fb_h`
- `seq`
- `req_counter`
- `payloadDefault`
- `pool`
- `sticky`
Removed:
- `client`
- `user_channel`
- `start_time`
- `ttstamp`
- `fb_dtsg`
- `email`
- `password`
So now the following variables remain:
- `uid` - A readonly documented `@property`
- `req_url` - Known external dependency, see #403
- `ssl_verify` - Documented
- `listening` - Documented
So overall, this is a _breaking change_, but it only changes undocumented variables, so I'll just bump the minor version number.
> Clean up `Client` variables

- fbchat/_client.py
- fbchat/_state.py
Move state handling into new `State` model.
This is done to extract code from `Client`, and get a better overview of where we're modifying global state (so that we can make the library thread safe in the future).
This (should) contain no breaking changes.
This model is currently private, but in the future, we might make it public as a sort of "low-level" API
> State refactor

- fbchat/_client.py
- fbchat/_util.py
Normalizes parsing of a lot of requests that were returning the same kind of JSON data. (We were already doing this to some extent, so I've just expanded on this). This should also improve the consistency of error messages.
This builds upon #435, in there, I moved all the remaining requests that din't return JSON data into the `State` model, and as such, all requests in `Client` now return JSON data (and we can remove boilerplate/special casing!)
> Clean up requests

- fbchat/_client.py
- fbchat/_graphql.py
- Removed the `GraphQL` class in favor of helper functions
- Use natural `_graphql` namespace
This changes the signature of `Client.graphql_requests` to take dictionaries, but I don't think it matters, since people could use it anyhow (the `GraphQL` object was private API)
> Clean up GraphQL module

- fbchat/_client.py
- fbchat/_group.py
- fbchat/_message.py
- fbchat/_state.py
- fbchat/_thread.py
Move various request helpers (e.g. `Client._post`) into the `State` model. This is done so that we can slowly start moving implementations into the relevant models (instead of having them live in `Client`).
For example, the implementation for `Client.addUsersToGroup` could, and should, be moved to `Group.add_users`. ~(However, before we can do this, a bit more work is required on updating `._getSendData` and `._doSendRequest`)~
This PR should be fairly trivial to review, one commit at a time.
> Move requests into state

- fbchat/_client.py
- fbchat/_file.py
- fbchat/_group.py
- fbchat/_location.py
- fbchat/_message.py
- fbchat/_plan.py
- fbchat/_thread.py
- fbchat/_user.py
- fbchat/_util.py
Replaces #278 and closes #277.
Use timezone-aware [`datetime.datetime`](https://docs.python.org/3/library/datetime.html#datetime.datetime) and [`datetime.timedelta`](https://docs.python.org/3/library/datetime.html#datetime.timedelta), instead of the raw "timestamp" values.
Thanks to @tcmal for their original PR.
> Use datetime/timedelta objects

- fbchat/_client.py
Currently `mark_as_read()` and `mark_as_unread()` call now() to determine the read timestamp to push to Facebook.
This can create a race condition if:
* Caller read message m1
* Caller calls `mark_as_read()`
* In the meantime, another message, m2 is received in the same thread
* `_read_status()` gets its timestamp calling `now()`, which is after `m2.timestamp` , but m2 hasn't been read yet
* As a result, m2 is marked as read while it hasn't been
This change adds an optional `timestamp` argument to `mark_as_read()` and `mark_as_unread()` to solve this issue (the caller *should* set this argument to the timestamp of the last message that been read)
> Add a optional timestamp parameter to mark_as_read and mark_as_unread

- fbchat/_client.py
- fbchat/_mqtt.py
- fbchat/_user.py
- fbchat/_util.py
- pyproject.toml
Uses the `paho.mqtt.python` library to add support for MQTT over WebSockets. @tulir's fork `fbchat-asyncio` has been very helpful in implementing this!
_This is fully backwards compatible!_
Fixes #490, fixes #483, fixes #460 and fixes #430.
After this is done, and has been released for a while (so it'll have some time to be tested in real world scenarios), I'll make an equivalent PR to `master`.
> Add WebSocket/MQTT support

- examples/basic_usage.py
- examples/echobot.py
- examples/interract.py
- fbchat/__init__.py
- fbchat/_client.py
- fbchat/_group.py
- fbchat/_message.py
- fbchat/_page.py
- fbchat/_plan.py
- fbchat/_thread.py
- fbchat/_user.py
- fbchat/_util.py
- tests/test_group.py
- tests/test_message.py
- tests/test_page.py
- tests/test_plan.py
- tests/test_plans.py
- tests/test_user.py
- Refactored message sending
- Split `User` into `User`/`UserData`
- Split `Group` into `Group`/`GroupData`
- Split `Page` into `Page`/`PageData`
- Split `Plan` into `Plan`/`PlanData`
- Split `Message` into `Message`/`MessageData`
Now there's a distinction between user created objects (e.g. `User`), and fetched objects (e.g. `UserData`).
This allows us to make some fields in the classes required (e.g. `UserData.name` is now guaranteed to not be `None`).
> Split models

- examples/fetch.py
- fbchat/_client.py
- fbchat/_file.py
- fbchat/_message.py
- fbchat/_thread.py
- fbchat/_util.py
- tests/test_file.py
Make the following methods return an iterable, so that we can batch requests where necessary
Fixes #503
> Refactor limits

- fbchat/_state.py
Facebook decided they needed an "Accept" header to return data on request and that broke fbchat
> Fix AttributeError on login

- fbchat/_client.py
Seems like it was leftover from some other function, probably one to handle both Added and Removed :)
> Remove add_reaction for onReactionAdded in docs
