fbchat-dev/fbchat

fbchat/__init__.py
fbchat/client.py
fbchat/utils.py
setup.py

Fix login and sendMessage
but I can't fix getThreadList() and getUsers()

Fix login and sendMessage

---

setup.py

The library errors out without lxml so I added it to the dependencies.

added lxml to dependencies

---

fbchat/__init__.py
fbchat/client.py
fbchat/utils.py

* Listening for new messages
* Add functions to be overwritten by users (on_message, on_typing, on_read ...)
* Default on_read actions (mark message as delivered & read)

New features

---

README.rst

Added a brief Introduction for people who's starting.

Improving README

---

fbchat/utils.py

JSON was previously crashing with the get_json(text), as mentioned in #25 and #31. Thanks to @blcc for the code to fix it.

Fix JSON load error issue #25 and #31

---

README.rst
fbchat/client.py
fbchat/utils.py

**DIGEST OF CHANGES**
**clients.py**:
Cloned data to be exact payload the js project is sending in send to fix #55 
Changed fbid in _parseMessage to fix #57 
If debug then print payload that is being sent on send
Added getUserInfo to add feature request #47 
**utils.py** :
Added generateOfflineThreadingID and getSignatureID which are clones of the same code in js project
**readme**  :
Added Echobot example 
Added getUserInfo example

Fixed #55 , send fail due to api change.

---

README.rst
fbchat/client.py
fbchat/utils.py

Retry login feature. Client.__init__ now takes max_retries (default 5) . #58

Retry login feature added

---

fbchat/client.py

Made getThreadInfo similar to send in that it has a parameter for whether a chat is with a group or a single user.

Added support for group threds in getThreadInfo

---

fbchat/client.py

remove_user_from_chat(threadID, userID)

Update client.py to kick chat participants, rename threads

---

fbchat/client.py

Jut followed the recipe in the issue

Update client.py to post to groups (Issue #63)

---

fbchat/client.py

Added error handling when sending messages

---

fbchat/client.py

Added functionality to add users in `send`
Fixed sending messages to groups (Sending empty `other_user_fbid` does
not work. It has to be omitted!)
Added new `on_message`, which gets `recipient_id` and `thread_type`.
This will help people sending messages to groups greatly! It also no
longer receives `name`, since this parameter isn't used.
Added event functions `on_people_added` and `on_person_removed`, and
their corresponding calls.

Added new functions and events. Also fixed sending messages to groups.

---

README.rst
fbchat/client.py

This uses some fairly unknown functions from the "requests" library.
Also, I fixed a spelling mistake

Added functions to save and load session cookies to and from file

---

fbchat/client.py

Apparently, python doesn't work the way i expected, when it comes to
overriding functions

Fixed some bugs

---

fbchat/client.py

Adding 2FA support for #110  
Added new function _2FA to handle the 5 steps of the 2FA request.
1. Input 2FA code
2. Remember Browser (Selects 'Save Browser')
3. FB Checkup
4. Confirm Login Attempt
5. Remember Browser _again_ (Selects 'Save Browser')
Sometimes, there isn't a FB Checkup, so added returns after every 2FA step to return back to main login function if the URL contains home.php.

Add 2FA Support

---

fbchat/client.py

I needed to implement this feature for an application I'm developing, and thought that this could be useful for other people too.

added the hability to control fbchat from an external event loop

---

fbchat/client.py

fix inconsistencies, remove some deprecated and unused things

---

.gitignore
fbchat/client.py
fbchat/models.py
fbchat/utils.py
tests.py

Will add several more I think and then it will be good to go
On a separate note, on every deprecation message we need to write something "will be removed in version 1.3" or smth. It's bad to keep a spaghetti of old and new code in the same plate.

Add more events and send methods, some fixes

---

fbchat/client.py

Handle the case when actions are missing in the payload

Actions can be missing

---

fbchat/graphql.py

The participant_customizations field is sometimes an empty array

Handle empty participant_customizations field

---

fbchat/client.py

Detail:
https://github.com/carpedm20/fbchat/issues/175
https://github.com/Schmavery/facebook-chat-api/issues/202
DO NOT MERGE THIS YET.

Fix issue when running for long time

---

fbchat/client.py
fbchat/graphql.py
fbchat/models.py

fetchThreadInfo and fetchThreadList both pull the message_count for each thread.
The Thread model has also been updated with a message_count.

Added Message Count to thread information

---

fbchat/utils.py

Should be pretty self-explanatory

Fix UNKNOWN gender in graphql requests

---

fbchat/client.py
requirements.txt

Sorry, I didn't know how to split the commits into different PR's
The changes to client.py are tested and working, as per [this issue](https://github.com/carpedm20/fbchat/issues/205)
The changes to the requirements are made due to [this issue](https://github.com/carpedm20/fbchat/issues/204)

Fixes 2FA bug and updates pip requirements

---

fbchat/client.py

(Fix the last PR #210)
sendImage(), sendLocalImage(), and sendRemoteImage() support different data types, but some keys need to change for GIF specially.

Add Gif support to send(Local/Remote)Image

---

docs/intro.rst
examples/echobot.py
examples/removebot.py
fbchat/client.py
fbchat/models.py
fbchat/utils.py

- Added new class `Attachment` (And subclasses of that)
- Modified `Message` class to match response properly
- `onMessage` now recieves an extra parameter, `message_object`, which is an object of `Message`, that contains the message, any attachments, the emoji size, and any @mentions
- (`Message` class may also be used in the future to send messages with @mentions)
- Added `fetchImageUrl`, which fetches an image download link from image id (fixes #84)
I'm putting this here to give everyone a chance to see what I've added, and to make comments on it. I'll merge this in a few days ;)

Attachment and @mention support in `onMessage`

---

fbchat/client.py
fbchat/utils.py

Added new feature to send an event reminder to a thread. It only creates a new event, but does not update an old one, if there already is an event under the same name.

new feature eventReminder added

---

fbchat/client.py
fbchat/graphql.py
fbchat/models.py

Updated for compatibility with python2.7

Added initial integration for messenger rooms

---

fbchat/client.py

checkRequest --> check_request

typo in function name

---

fbchat/client.py

Message attachments are structured differently now (no more 'attach_type'), and shared items come as 'extensible_attachment'.

Fix attachment parsing for newer structure

---

fbchat/graphql.py
fbchat/models.py

Get audio message information for fetchThreadMessages()

modify AudioAttachment function

---

fbchat/client.py

Restored onFriendRequest functionality

---

fbchat/client.py
fbchat/graphql.py
tests.py

Quick fix for function `fetchThreadList()` as Facebook migrated it to GraphQL.

Added GraphQL alternative to fetchThreadList; fixes #241

---

fbchat/client.py
fbchat/models.py

Fix ThreadLocation to work with new GraphQL and archived threads

---

fbchat/client.py
fbchat/utils.py

I fixed changeThreadTitle method because of #1545065 error and
added new methods:
`changeThreadImage(self, image_id, thread_id=None, thread_type=ThreadType.USER):`
`changeThreadImageRemote(self, image_url, thread_id=None, thread_type=ThreadType.USER):`
`changeThreadImageLocal(self, image_path, thread_id=None, thread_type=ThreadType.USER):`

Fixed changeThreadTitle and added changeThreadImage

---

fbchat/client.py
fbchat/utils.py

Added create group url to the utils.py
Added create group def to the client.py
#250

Added Create Group

---

fbchat/client.py
fbchat/graphql.py
fbchat/models.py

Because [Facebook](https://facebook.com/) connected rooms with groups, I'm doing the same in `fbchat`!
I removed `Room` model and added new parameters to `Group` model:
> admins
> approval_mode
> approval_requests
> join_link

Merge `Room` with `Group`

---

fbchat/client.py

As in the title, I removed unnecessary code, this variables aren't used anywhere in the code.

[Enhancement] Remove unnecessary code

---

fbchat/client.py
fbchat/graphql.py
fbchat/models.py
fbchat/utils.py

Added:
- Detecting extensible attachments
- New models: `ShareAttachment`, `LocationAttachment`, `LiveLocationAttachment`
- Fetching live user location
- Unreacting to messages
- New methods `sendLocation` and `sendPinnedLocation`
- New `on` methods: `onReactionAdded`, `onReactionRemoved`, `onBlock`, `onUnblock`, `onLiveLocation`
- Fixed `size` of attachments
- Sending voice clips
- Unsending messages
- `deleted` Message attribute

[Feature] Extensible attachments

---

fbchat/client.py

First `C` letter in `FBchatException` should be lowercase.
`FBChatException` ---> `FBchatException`

Fixed typos in FBchatException

---

.travis.yml
CONTRIBUTING.rst
README.rst
docs/conf.py
examples/basic_usage.py
examples/echobot.py
examples/fetch.py
examples/interract.py
examples/keepbot.py
examples/removebot.py
fbchat/__init__.py
fbchat/client.py
fbchat/graphql.py
fbchat/models.py
fbchat/utils.py
pyproject.toml
tests/conftest.py
tests/test_fetch.py
tests/test_plans.py
tests/test_polls.py
tests/test_send.py
tests/test_tests.py
tests/test_thread_interraction.py
tests/utils.py

This transitions our code to use [`black`](https://github.com/ambv/black). In this PR, there aren't any manual code changes, the only relevant changes are in `pyproject.toml`, `.travis.yml`, `README.rst` and `CONTRIBUTING.rst`.
I know this will confuse `git blame` _a lot_, but it's really the best way forward in modernizing the library.

Use `black` for formatting

---

docs/conf.py
fbchat/_attachment.py
fbchat/_file.py
fbchat/_group.py
fbchat/_location.py
fbchat/_message.py
fbchat/_page.py
fbchat/_plan.py
fbchat/_poll.py
fbchat/_quick_reply.py
fbchat/_sticker.py
fbchat/_thread.py
fbchat/_user.py
pyproject.toml

Use [attrs](https://www.attrs.org/) to declare our models. This will allow us to vastly reduce duplication in the `__init__` methods, and perhaps it'll also help with #302?

Use `attrs`

---

fbchat/_thread.py

Color names are from https://www.htmlcsscolor.com/

Add new colors

---

fbchat/_client.py
fbchat/_graphql.py
fbchat/_message.py
fbchat/graphql.py

Add possibility to reply to messages and fetch the replied messages.
~ Closes #410 
```python
mid = client.sendMessage("Hey")
client.send(Message(texy="Heyah!", reply_to_id=mid))
```
```python
messages = client.fetchThreadMessages()
messages[0].replied_to
```

Add replying to messages

---

fbchat/_client.py

```python
client.sendLocation(LocationAttachment(50, 50), message=Message("Additional message"))
```

Add message to sending location

---

fbchat/_util.py

Fix sending remote files with URLs containing GET parameters

---

fbchat/_client.py
fbchat/_exception.py
fbchat/_graphql.py
fbchat/_util.py

- Make error handling more targeted/explicit (so that we don't attempt to run error handling on things that don't need it)
- Improve error handling in general (I've added a few helpful descriptions / exception names when we encounter a known error)
Builds upon #436

More explicit error handling

---

docs/conf.py
fbchat/_client.py

Use [Google docstring style](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings). Uses the `napoleon` Sphinx extension.
When reviewing, it's recommended that you review the commits that convert to the style, briefly (they were done mostly with simple `grep`s).

Google docstring style

---

.github/ISSUE_TEMPLATE/bug_report.md
.travis.yml
CONTRIBUTING.rst
README.rst
docs/conf.py
docs/examples.rst
docs/faq.rst
docs/index.rst
docs/install.rst
docs/intro.rst
docs/spelling/fixes.txt
docs/spelling/names.txt
docs/spelling/technical.txt
docs/todo.rst
examples/interract.py
fbchat/_attachment.py
fbchat/_client.py
fbchat/_core.py
fbchat/_exception.py
fbchat/_file.py
fbchat/_group.py
fbchat/_message.py
fbchat/_page.py
fbchat/_plan.py
fbchat/_sticker.py
fbchat/_thread.py
fbchat/_user.py
pyproject.toml

Builds upon #454 
Use [sphinxcontrib-spelling](https://sphinxcontrib-spelling.readthedocs.io/) to fix documentation and docstring spelling errors.

Add spell check

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/api.rst
fbchat/__init__.py
fbchat/_client.py
fbchat/_exception.py
fbchat/_group.py
fbchat/_state.py
fbchat/_thread.py
tests/conftest.py
tests/test_base.py
tests/utils.py

Removed various deprecated, unwanted or unneeded functionality.
If your "favorite feature" was touched by this, please comment on this PR, and I'll see what we can do!

Various removals

---

fbchat/_attachment.py
fbchat/_file.py
fbchat/_group.py
fbchat/_location.py
fbchat/_message.py
fbchat/_page.py
fbchat/_plan.py
fbchat/_poll.py
fbchat/_quick_reply.py
fbchat/_sticker.py
fbchat/_thread.py
fbchat/_user.py
tests/test_attachment.py
tests/test_core.py
tests/test_file.py
tests/test_graphql.py
tests/test_group.py
tests/test_location.py
tests/test_message.py
tests/test_page.py
tests/test_plan.py
tests/test_poll.py
tests/test_quick_reply.py
tests/test_sticker.py
tests/test_thread.py
tests/test_user.py
tests/test_util.py

- Add unit tests for most `_from_X` methods
- Make classes comparable
- Remove custom init methods
- Fix `LiveLocation.expires_at` parsing
Overall, fairly simple additions, yet quite a hughe impact on maintainability!

Add unit tests

---

examples/basic_usage.py
examples/echobot.py
examples/fetch.py
examples/interract.py
examples/keepbot.py
examples/removebot.py
fbchat/__init__.py
fbchat/_client.py
fbchat/_session.py

Rename `State` -> `Session`, and make the class public.
The intention is that `Session` is now the main entry point for the library.
Part of [this card](https://github.com/carpedm20/fbchat/projects/2#card-26165228)

Public session

---

fbchat/_sticker.py

improve animated sticker support

---

fbchat/__init__.py
fbchat/_client.py
fbchat/_exception.py
fbchat/_graphql.py
fbchat/_message.py
fbchat/_plan.py
fbchat/_poll.py
fbchat/_session.py
fbchat/_thread.py
fbchat/_util.py
tests/test_base.py
tests/test_exception.py
tests/test_plans.py
tests/test_send.py
tests/test_thread_interraction.py
tests/test_util.py
tests/utils.py

Various exception improvements, including:
- Wrapping `requests` exceptions
- Adding dedicated `GraphQLError`
- And a lot of small fixes, generally just making everything nicer 😊

Improve exceptions

---

fbchat/_client.py

I added onPendingMessage function that i requested in this issue: https://github.com/carpedm20/fbchat/issues/508
fixes #508

Add onPendingMessage function

---

examples/session_handling.py

json.dump() receives object as first argument and File Pointer as 2nd argument.

First Object then File Pointer
